### ISSUE TITLE
replace mess hall and private chat with Gitter embed

### ISSUE THREAD

**Issue by Matthew-Burfield** [FCC-Alumni/alumni-network#158] opened 2017-05-10 23:57 UTC
I don’t really understand the need/want for the Mess Hall.

There are already many technologies that focus exclusively on chat and therefore do the chat better. (slack/gitter/messenger etc)

I think FCCAN should stick to the collaboration aspect, and utilise the pre-existing technologies like slack for live chatting instead of trying to re-create the wheel.

**Comment by no-stack-dub-sack** [comment] 2017-05-11 00:06
@Matthew-Burfield How do you feel about private chat?

**Comment by Matthew-Burfield** [comment] 2017-05-11 00:20
@no-stack-dub-sack Private chat is great! I'd prefer to have all messages from FCCAN come to me via private chat than email for example.

And then that chat can easily be moved to an actual chat platform later if required

**Comment by bonham000** [comment] 2017-05-11 02:04
Yes, this is the whole point made in the info box in the chat window. And partially why I think bonus features like markdown should be deliberately not supported. However, private chat was essentially the main feature targeted toward fostering collaboration and communication between interested members, within FCCAN itself.

I still think the global chat is valuable but that the more valuable feature is the private caht.

**Comment by smiller171** [comment] 2017-06-26 16:08
Gitter supports private chats. Why not use a Gitter embed instead of reinventing the wheel?

**Comment by smiller171** [comment] 2017-06-26 16:08
That would also allow people to easily receive chat notifications on mobile.

**Comment by no-stack-dub-sack** [comment] 2017-06-27 01:53
@bonham000 is the creator of that Chat feature - looping him in to see what he thinks. It was pretty cool creating this, but I can see the sense in having mobile notifications, more robust features, etc.

**Comment by smiller171** [comment] 2017-06-27 14:47
Yeah, writing a chat app is a fun project, but for production use it's probably better to use something that already exists.

**Comment by smiller171** [comment] 2017-06-28 19:42
Confirmed that you can embed Gitter with a simple iFrame.

**Comment by no-stack-dub-sack** [comment] 2017-06-29 02:57
@smiller171 @bonham000 @Matthew-Burfield @anyoneWhoWantsToHelp
So I've thrown together a working prototype of the the gitter embed chat model, which embeds an FCCAN channel where this chat is now, and links to individual channels when entering into a private chat, i.e. `https://gitter.im/no-stack-dub-sack`

but this presents some issues since not all users are guaranteed to have gitter

Basically, if the user is not a member, the page 404s, so we need to detect that and show a message about inviting a user to gitter or something. Was having trouble just now trying to get this to work, since trying to ping the `gitter.im/username` endpoint via the app is giving me a 401 error. I guess I need to use their API to authorize, but that seems to be overkill, and I'm also not seeing a straightforward solution to check if a username exists. 

anyone have any ideas on how to get around this?

I'll PR the current solution just by way of example but this should not be merged in for now.

**Comment by smiller171** [comment] 2017-06-29 13:37
@no-stack-dub-sack If I try to curl a gitter user that doesn't exist I get a 404. Could you paste the code you are using that's getting a 401?

**Comment by smiller171** [comment] 2017-06-29 13:49
I can think of two solutions. Probably both should be used

1. When a user signs up, check if they have Gitter and ask them to sign up if they don't
2. Check if a user has gitter and if they don't offer other options like email instead of chat

**Comment by no-stack-dub-sack** [comment] 2017-06-30 03:35
@smiller171 I tried 2 different approaches, both using `axios` - this is the same way we checked for certs, basically - if the page 404s, it redirects and if the redirect count is greater than `0`, we know the page is invalid. I tried this on the client, and I was running into CORS issues because locally the app is served over https and we're trying to ping an https endpoint. So I tried this on the server as well and was getting the 401, I'm guessing because the app itself is not "logged in" or authorized with gitter. But when I do it in the browser I can get the 404 because I'm logged in. At least this is my guess. 

Here's the basic gist of the code I tried on the server: 

```js
router.post('/api/is-gitter-user', (req, res) => {
  const { username } = req.body;
  axios.get(`https://gitter.im${username}`)
  .then((response) => {
    if (response.request._redirectCount === 0) {
      res.json({ isGitterUser: true });
    } else {
      res.json({ isGitterUser: false });
    }
  })
  .catch((err) => {
    if (err) res.json({ isGitterUser: false });
  });
});
```
Then I was just using axios from the client to hit this api with the user info. I was getting the 401 unauthorized error with this (I think this code is mostly right, I just threw it together again really quick).

To your suggestions, yes I think both of those could work, and @bonham000 suggested the first solution as well. But with that option, how would we retroactively enforce this? Also, I am hesitant to make the signup process more complex out of fear that people just won't want to do it.

**Comment by smiller171** [comment] 2017-06-30 14:37
@no-stack-dub-sack It looks like you're missing a `/`. Instead of ``axios.get(`https://gitter.im${username}`)`` Shouldn't it be ``axios.get(`https://gitter.im/${username}`)``?

**Comment by smiller171** [comment] 2017-06-30 14:38
I can use curl and get a 404, where I am definitely not authenticated, so that's not the issue

```
➜  ~ curl -I https://gitter.im/username
HTTP/1.1 200 OK
Content-Length: 8508
Content-Type: text/html; charset=utf-8
Date: Thu, 29 Jun 2017 13:37:48 GMT
ETag: W/"213c-MfChlOHdyVTeeDShKBc444CHncA"
Server: nginx
set-cookie: g_session=s%3AtF5B5Zfe9zEI_cGOqn_HKC_hwvjsxIEK.%2FNL1DlApF3mXSk7Ot4JrQVo22LNaOpn1VcAOl%2BTmw8w; Domain=.gitter.im; Path=/; Expires=Thu, 29 Jun 2017 17:37:48 GMT; HttpOnly; Secure
X-Server-ID: webapp-02
X-Upstream: 127.0.0.1:5021
Connection: keep-alive
```

**Comment by smiller171** [comment] 2017-06-30 15:40
but your method of using redirectCount seems like a hack. You should probably just check the status code (code untested)

```javascript
router.post('/api/is-gitter-user', (req, res) => {
  const { username } = req.body;
  axios.get(`https://gitter.im${username}`)
  .then((response) => {
    if (199 < response.status < 300) { //Passes if response is a 2xx code
      res.json({ isGitterUser: true });
    } else if (response.status == 404) {
      res.json({ isGitterUser: false });
    } else {
      //handle unknown error
    }
  })
  .catch((err) => {
    if ( err.status == 404 ) {
      res.json({ isGitterUser: false });
    } else {
      //handle unknown error
    }
  });
});
```

**Comment by no-stack-dub-sack** [comment] 2017-06-30 22:01
@smiller171 Yes -- was missing a slash, but that wasn't the problem since this wasn't the exact code. And double yes - that's a good point, we couldn't check the status for the certs because it redirected to a valid page, I forgot that I could just do this directly. Makes way more sense :smile:

But still, I think I will still get the 401. I'm not really familiar with CURL, but I'll try your above solution and take some screenshots a bit later to show you what I am getting.

**Comment by smiller171** [comment] 2017-07-02 23:41
@no-stack-dub-sack cURL is just a command line tool for downloading files from http servers

**Comment by no-stack-dub-sack** [comment] 2017-07-06 00:44
@smiller171 I know the basic gist of what it is, I should say, but have never used it. 

Also, I think what you were saying about this solution being hacky is true, though I just checked and when you are logged out and try to visit someone's direct chat channel, it redirects to login and still shows status 200. So maybe we still need to count redirects so we can warn that either someone either needs to login or that the user doesn't have gitter...

**Comment by smiller171** [comment] 2017-07-06 13:38
@no-stack-dub-sack Checking for that redirect and checking for 404 would be two different checks though, which should be displayed to the user differently. The former means the active user needs to log into Gitter and can be directed to do so. The latter means that the user they are trying to chat with does not have Gitter set up. This should be checked when their profile is first loaded, and the chat button should be disabled / greyed out to indicate that that user is not on Gitter

**Comment by no-stack-dub-sack** [comment] 2017-07-07 14:54
@smiller171 copy that. making good progress on this. Should have a PR in tonight that will be a solid POC. Then from there we can hopefully integrate a more seamless check during the login process. Once we're happy with this, I can then begin the arduous process of de-chatifying the codebase.  I have a separate branch going for this already, and it was quite a bit of work. Was prob premature though and I will likely need to redo it at some point due to complex merge conflicts that are sure to arise.

**Closed** 2017-07-08 22:46 UTC
Labels: beta, help wanted, post production
