### ISSUE TITLE
Can't unlike mess-hall comment or private chat

### ISSUE THREAD

**Issue by Mozar10** [FCC-Alumni/alumni-network#155] opened 2017-05-10 22:07 UTC
Site looks and works awesome !

This is a small issue, re-clicking the heart won't revoke (I'm tired, revoke works here right? lol) the original like.

**Comment by no-stack-dub-sack** [comment] 2017-05-10 22:45
@Mozar10 thanks! Duly noted. We will consider this. Shouldn't be to large a leap from what we already have. I'll ask @bonham000 what he thinks. But going to close this as duplicate of #154

**Closed by no-stack-dub-sack** 2017-05-10 22:45 UTC
